fix: 액츄에이터 설정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,6 +14,16 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      # build.gradle 내용 확인
+      - name: Print build.gradle content
+        run: cat build.gradle
+
+      - name: Print application.yml
+        run: cat src/main/resources/application.yml || echo "❌ application.yml not found"
+
+      - name: Print application-prod.yml
+        run: cat src/main/resources/application-prod.yml || echo "❌ application-prod.yml not found"
+
       # Docker Buildx 설정(빌드 최적화)
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
